services:
  redis:
    image: redis:7
    container_name: test_cache

  tests:
    image: loadimpact/k6:latest
    command: ["run", "--out", "influxdb=http://influxdb:8086", "--env", "SCENARIO=ten", "/scripts/eventApp.seats.loadTest.js"]
    volumes:
     - ./eventApp.seats.loadTest.js:/scripts/eventApp.seats.loadTest.js
    container_name: test_load
    depends_on:
      - events
      - influxdb

  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  database:
    image: postgres:17.0
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./../init.sql:/docker-entrypoint-initdb.d/init.sql
      - mentoring:/var/lib/postgresql/pgdata
    container_name: test_database

  events:
    image: eventapp
    build:
      dockerfile: ./EventsDockerfile
      context: ./../
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
      - ConnectionStrings__RedisConnection=redis
      - CACHING_DISABLED=false
    container_name: test_eventapp
    depends_on:
      - database
      - redis

volumes:
  mentoring: