services:
  redis:
    image: redis:7
    ##build:
    ##  dockerfile: ./RedisDockerfile
    ports:
      - 6379:6379
    container_name: mentoring_cache

  database:
    build: .
    image: postgres_mentoring
    volumes:
      - mentoring:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5400:5432
    container_name: mentoring_database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5555:80

  venues:
    image: venueapp
    build:
      dockerfile: ./VenuesDockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
    ports:
      - 8080:8080
    container_name: mentoring_venues
    depends_on:
      - database

  events:
    image: eventapp
    build:
      dockerfile: ./EventsDockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
      - ConnectionStrings__RedisConnection=redis
    ports:
      - 8081:8080
    container_name: mentoring_events
    depends_on:
      - database

  orders:
    image: orderapp
    build:
      dockerfile: ./OrdersDockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
      - ConnectionStrings__RedisConnection=redis
    ports:
      - 8082:8080
    container_name: mentoring_orders
    depends_on:
      - database

  payments:
    image: paymentapp
    build:
      dockerfile: ./PaymentDockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;User Id=postgres;Password=postgres;Database=postgres;
    ports:
      - 8083:8080
    container_name: mentoring_payments
    depends_on:
      - database

volumes:
  mentoring: