services:
  database:
    build: .
    volumes:
      - mentoring:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5400:5432
    container_name: mentoring_database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5555:80

volumes:
  mentoring: